@startuml DDD Models

class "UserAccount\n（ユーザーアカウント）" as UserAccount {
  ID *🔒
  氏名 *
  生年月日 *
  性別
  電話番号
  住所
  メールアドレス
  配送先[]
  ウォレット *
  注文履歴 *
  ---
}
note right:¥
* メールアドレスでログインするなら必須（今回はログイン考慮なし） ¥n¥
* 住所、配送先は登録が無くても注文時に毎回指定できる（作成時に住所不要）

class "🔒Email\n（メール）" as Email <<ValueObject>> {
  アドレス *
  ---
  送信
}

class "Cart\n（カート）" as Cart {
  (商品, 数量)[]
  ---
  商品を追加
  商品数量を変更
  商品を削除
  注文見積を作成
}

package Order {
  class "OrderHistory\n（注文履歴）" as OrderHistory {
    注文[]
    ---
    追加
    絞り込み
  }

  class "🔒OrderEstimation\n（注文見積）" as OrderEstimation <<ValueObject>> {
    単位注文見積[] *
    ---
    注文を実行
    合計金額を算出
  }

  class "🔒UnitOrderEstimation\n（単位注文見積）" as UnitOrderEstimation <<ValueObject>> {
    (商品, 単価, 数量)[] *
    送料 *
    配達業者 *
    ---
    合計金額を算出
    単位注文を作成
  }

  class "🔒Order\n（注文）" as Order {
    ID *
    単位注文[] *
    ---
    合計金額を算出
  }

  class "UnitOrder\n（単位注文）" as UnitOrder {
    ID *🔒
    日時 *🔒
    (商品, 単価, 数量)[] *🔒
    送料 *🔒
    配達業者 *🔒
    トラッキングID
    支払方法 *
    ステータス *
    ---
    合計金額を算出
    キャンセル
  }

  OrderHistory *-- Order

  OrderEstimation *-- UnitOrderEstimation
  OrderEstimation -> Order : <<Create>>

  UnitOrderEstimation -> UnitOrder : <<Create>>

  Order "1" *-- "1..*" UnitOrder
}


class "Merchandise\n（商品）" as Merchandise {
  ID *🔒
  名称 *
  現在価格 *
  販売者 *
  在庫 *
  説明 *
  レビュー[]
  ---
  レビュー平均点を算出
}

class "Seller\n（販売者）" as Seller {
  ID *🔒
  名称 *
  振込先 *
  住所 *
  電話番号 *
  メールアドレス *
  ---
  発注を依頼
  送金
}


package Payment {
  class "Wallet\n（ウォレット）" as Wallet {
    支払方法[]
    ---
    追加
    変更
    削除
  }

  class "🔒PaymentMethod\n（支払方法）" as PaymentMethod <<ValueObject>> {
    支払種別 *
    振込先
    クレジットカード
  }

  enum "PaymentType\n（支払種別）" as PaymentType {
    クレジットカード
    銀行振込
    代引
  }

  class "🔒CreditCard\n（クレジットカード）" as CreditCard <<ValueObject>> {
    カード番号 *
    有効期限 *
    名義人 *
  }

  class "CreditCardCompany\n（クレジットカード会社）" as CreditCardCompany {
    ID *🔒
    名称 *
    ---
    請求
  }

  Wallet o-- PaymentMethod

  PaymentMethod o-- PaymentType
  PaymentMethod o-- CreditCard

  CreditCard o-- CreditCardCompany
}


class "Courier\n（配送業者）" as Courier {
  ID *🔒
  名称 *
  電話番号 *
  メールアドレス *
  ---
  追跡
  追跡通知を登録
}

'--------------------

UserAccount "1" o- "0..1" Email
UserAccount "1" *-l- "1" Cart
UserAccount "1" *-- "1" Wallet
UserAccount "1" *-- "1" OrderHistory

Cart "1" o-- "0..*" Merchandise
Cart --> OrderEstimation : <<Create>>

UnitOrderEstimation "1" o-- "1" Courier

UnitOrder "1" o-- "1" Courier
UnitOrder o-- Merchandise

Merchandise "1..*" o-- "1" Seller



@enduml
